"""End-to-end checks for the backup workflow."""

BACKUP_ROOT = "/tmp/workstation-manager-e2e-backup"


def resolve_backup_archive_path(host) -> str:
    """Return the single backup archive path generated by the E2E backup flow."""

    # Act
    archive_path = host.check_output(
        "sh -lc %s",
        (
            "set -eu; "
            "archives=$(find /tmp/workstation-manager-e2e-backup -maxdepth 1 -type f "
            "-name 'workstation-manager-backup-*.tar.gz' | sort); "
            "[ \"$(printf '%s\\n' \"$archives\" | sed '/^$/d' | wc -l)\" -eq 1 ]; "
            "printf '%s' \"$archives\""
        ),
    )

    # Assert
    assert archive_path
    return archive_path


def resolve_backup_manifest_path(host) -> str:
    """Return the manifest path paired with the generated E2E backup archive."""

    # Arrange
    archive_path = resolve_backup_archive_path(host)

    # Act
    manifest_path = archive_path.removesuffix(".tar.gz") + ".manifest.txt"

    # Assert
    assert manifest_path
    return manifest_path


def test_backup_archive_and_manifest_exist(host) -> None:
    """The E2E backup flow should produce both the archive and its manifest."""

    # Arrange
    backup_archive = host.file(resolve_backup_archive_path(host))
    backup_manifest = host.file(resolve_backup_manifest_path(host))

    # Assert
    assert backup_archive.exists
    assert backup_archive.is_file
    assert backup_manifest.exists
    assert backup_manifest.is_file


def test_backup_manifest_records_expected_entries(host) -> None:
    """The backup manifest should reflect the generated archive and core inputs."""

    # Arrange
    user_home = host.check_output("printf '%s' \"$HOME\"")
    archive_path = resolve_backup_archive_path(host)
    manifest_path = resolve_backup_manifest_path(host)
    bookmark_export_path = f"{BACKUP_ROOT}/browser-bookmarks/Default/Bookmarks.json"

    # Act
    archive_line = host.run(
        "grep -Fx %s %s",
        f"archive\t{archive_path}",
        manifest_path,
    )
    dry_run_line = host.run("grep -Fx 'dry_run\t0' %s", manifest_path)
    managed_profiles_line = host.run(
        "grep -Fx %s %s",
        (
            "include\tmanaged-browser-profiles\t"
            f"{user_home}/.local/share/workstation-manager/browser-profiles"
        ),
        manifest_path,
    )
    bookmark_export_line = host.run(
        "grep -Fx %s %s",
        f"export\tchrome-bookmarks\t{bookmark_export_path}",
        manifest_path,
    )

    # Assert
    assert archive_line.succeeded
    assert dry_run_line.succeeded
    assert managed_profiles_line.succeeded
    assert bookmark_export_line.succeeded


def test_backup_archive_contains_managed_browser_profiles(host) -> None:
    """The generated archive should contain the managed browser profile root."""

    # Arrange
    backup_archive_path = resolve_backup_archive_path(host)

    # Act
    archive_listing = host.run(
        "tar -tzf %s | grep -F %s",
        backup_archive_path,
        ".local/share/workstation-manager/browser-profiles/personal",
    )

    # Assert
    assert archive_listing.succeeded


def test_backup_exports_chrome_bookmarks_as_standalone_json(host) -> None:
    """The backup flow should export bookmark JSON separately from raw Chrome data."""

    # Arrange
    bookmark_export = host.file(
        f"{BACKUP_ROOT}/browser-bookmarks/Default/Bookmarks.json"
    )

    # Act
    has_repo_bookmark = bookmark_export.contains(
        '"url": "https://github.com/neilime/workstation-manager"'
    )

    # Assert
    assert bookmark_export.exists
    assert bookmark_export.is_file
    assert bookmark_export.user == host.check_output("whoami")
    assert has_repo_bookmark
