"""End-to-end checks for the backup workflow."""

BACKUP_ROOT = "/tmp/workstation-manager-e2e-backup"


def resolve_backup_archive_path(host) -> str:
    """Return the single backup archive path generated by the E2E backup flow."""

    # Act
    archive_path = host.check_output(
        "sh -lc %s",
        (
            "set -eu; "
            "archives=$(find /tmp/workstation-manager-e2e-backup -maxdepth 1 -type f "
            "-name 'workstation-manager-backup-*.tar.gz' | sort); "
            "[ \"$(printf '%s\\n' \"$archives\" | sed '/^$/d' | wc -l)\" -eq 1 ]; "
            "printf '%s' \"$archives\""
        ),
    )

    # Assert
    assert archive_path
    return archive_path


def resolve_backup_manifest_path(host) -> str:
    """Return the manifest path paired with the generated E2E backup archive."""

    # Arrange
    archive_path = resolve_backup_archive_path(host)

    # Act
    manifest_path = archive_path.removesuffix(".tar.gz") + ".manifest.txt"

    # Assert
    assert manifest_path
    return manifest_path


def resolve_backup_git_inventory_path(host) -> str:
    """Return the Git inventory path paired with the generated E2E backup archive."""

    # Arrange
    archive_path = resolve_backup_archive_path(host)

    # Act
    inventory_path = archive_path.removesuffix(".tar.gz") + ".git-repositories.json"

    # Assert
    assert inventory_path
    return inventory_path


def resolve_backup_restore_command_path(host) -> str:
    """Return the restore-command sidecar paired with the generated E2E backup archive."""

    archive_path = resolve_backup_archive_path(host)
    restore_command_path = (
        archive_path.removesuffix(".tar.gz") + ".restore-command.txt"
    )
    assert restore_command_path
    return restore_command_path


def test_backup_archive_and_manifest_exist(host) -> None:
    """The E2E backup flow should produce the archive plus its core sidecars."""

    # Arrange
    backup_archive = host.file(resolve_backup_archive_path(host))
    backup_manifest = host.file(resolve_backup_manifest_path(host))
    backup_restore_command = host.file(resolve_backup_restore_command_path(host))

    # Assert
    assert backup_archive.exists
    assert backup_archive.is_file
    assert backup_manifest.exists
    assert backup_manifest.is_file
    assert backup_restore_command.exists
    assert backup_restore_command.is_file


def test_backup_git_inventory_exists(host) -> None:
    """The backup flow should emit a Git inventory sidecar for dev-projects."""

    # Arrange
    backup_git_inventory = host.file(resolve_backup_git_inventory_path(host))

    # Assert
    assert backup_git_inventory.exists
    assert backup_git_inventory.is_file


def test_backup_outputs_are_owned_by_the_managed_user(host) -> None:
    """Elevating the controller must not create root-owned recovery artifacts."""

    expected_user = host.check_output("id -un")
    for path in (
        BACKUP_ROOT,
        resolve_backup_archive_path(host),
        resolve_backup_manifest_path(host),
        resolve_backup_git_inventory_path(host),
        resolve_backup_restore_command_path(host),
    ):
        assert host.file(path).user == expected_user


def test_backup_manifest_records_expected_entries(host) -> None:
    """The backup manifest should reflect the generated archive and core inputs."""

    # Arrange
    archive_path = resolve_backup_archive_path(host)
    manifest_path = resolve_backup_manifest_path(host)
    git_inventory_path = resolve_backup_git_inventory_path(host)
    restore_command_path = resolve_backup_restore_command_path(host)

    # Act
    archive_line = host.run(
        "grep -Fx %s %s",
        f"archive\t{archive_path}",
        manifest_path,
    )
    dry_run_line = host.run("grep -Fx 'dry_run\t0' %s", manifest_path)
    git_inventory_line = host.run(
        "grep -Fx %s %s",
        f"export\tgit-repositories\t{git_inventory_path}",
        manifest_path,
    )
    restore_command_line = host.run(
        "grep -Fx %s %s",
        f"export\trestore-command\t{restore_command_path}",
        manifest_path,
    )

    # Assert
    assert archive_line.succeeded
    assert dry_run_line.succeeded
    assert git_inventory_line.succeeded
    assert restore_command_line.succeeded


def test_backup_restore_command_matches_the_generated_archive(host) -> None:
    """The restore-command sidecar should be ready to paste on another machine."""

    archive_path = resolve_backup_archive_path(host)
    restore_command = host.file(resolve_backup_restore_command_path(host)).content_string
    assert restore_command.startswith("wget -qO- https://raw.githubusercontent.com/")
    assert host.file(resolve_backup_restore_command_path(host)).mode == 0o600
    assert restore_command.endswith(
        f"WORKSTATION_MANAGER_RESTORE_ARCHIVE={archive_path} sh -s -- setup\n"
    )


def test_backup_browser_export_matches_manifest(host) -> None:
    """A generated browser sidecar must have exactly one matching manifest record."""

    browser_export_path = resolve_backup_archive_path(host).removesuffix(".tar.gz") + ".browser-profiles.json"
    browser_export = host.file(browser_export_path)
    manifest = host.file(resolve_backup_manifest_path(host)).content_string
    export_lines = [line for line in manifest.splitlines() if line.startswith("export\tbrowser-profiles\t")]
    assert export_lines == ([f"export\tbrowser-profiles\t{browser_export_path}"] if browser_export.exists else [])
    if browser_export.exists:
        assert browser_export.is_file
        assert browser_export.mode == 0o600
        assert browser_export.user == host.check_output("id -un")


def test_backup_verifies_recovery_without_skips(host) -> None:
    """Prepared recovery sources must pass the normal noninteractive checks."""

    manifest = host.file(resolve_backup_manifest_path(host)).content_string
    assert "recovery_skipped\t" not in manifest
    assert "recovery_status\tincomplete" not in manifest


def test_backup_exports_git_inventory_for_dev_projects(host) -> None:
    """The backup flow should record Git remotes and branch state for dev-projects."""

    # Arrange
    git_inventory = host.file(resolve_backup_git_inventory_path(host))

    # Act
    has_repo_path = git_inventory.contains('"relative_path": "client-restore"')
    has_origin_name = git_inventory.contains('"primary_remote_name": "origin"')
    has_origin_url = git_inventory.contains(
        '"primary_remote_url": "/tmp/workstation-manager-e2e-origin-client-restore.git"'
    )
    has_branch = git_inventory.contains('"branch": "main"')

    # Assert
    assert has_repo_path
    assert has_origin_name
    assert has_origin_url
    assert has_branch


def test_backup_omits_ignored_dependency_repositories(host) -> None:
    """The dependency fixture must stay outside the project recovery inventory."""

    git_inventory = host.file(resolve_backup_git_inventory_path(host))
    assert not git_inventory.contains('"relative_path": "client-restore/tools/vendor/')


def test_backup_archive_omits_git_ignored_files_and_keeps_local_edits(host) -> None:
    """Project recovery should retain source edits without ignored dependencies or secrets."""

    archive_path = resolve_backup_archive_path(host)
    members = host.check_output("tar -tzf %s", archive_path).splitlines()
    assert not any("/.git/" in name or name.endswith("/.git") for name in members)
    assert not any("/tools/vendor/" in name or name.endswith(".private") for name in members)
    prefix = "Documents/dev-projects/client-restore/"
    assert prefix + "local-note.txt" in members
    assert host.check_output("tar -xOzf %s %s", archive_path, prefix + "tracked.txt") == "remote-base\nlocal-change"
    assert host.file(archive_path).mode == 0o600
