"""Create native Brave profiles and apply declared colors and avatars."""

from __future__ import annotations

import json
import os
import re
import tempfile
from collections.abc import Iterator
from pathlib import Path

from ansible_collections.neilime.workstation_setup.plugins.module_utils.browser_profile_avatar import (
    AVATAR_FILENAME,
    decode_avatar_png,
)
from ansible_collections.neilime.workstation_setup.plugins.module_utils.browser_profile_paths import (
    BrowserProfilePathsPlanner,
)


def _read_json(path: Path) -> dict:
    """Read settings strictly; malformed or symlinked files must never be replaced."""

    if path.is_symlink():
        raise ValueError(f"Refusing symlinked browser settings: {path.name}")
    if not path.exists():
        return {}
    with path.open(encoding="utf-8") as handle:
        data = json.load(handle)
    if not isinstance(data, dict):
        raise ValueError(f"Expected a JSON object in {path.name}")
    return data


def _object(parent: dict, key: str) -> dict:
    """Get or create one settings object, rejecting malformed existing values."""

    value = parent.setdefault(key, {})
    if not isinstance(value, dict):
        raise ValueError(f"Expected a JSON object for {key}")
    return value


def _write_file(path: Path, data: dict | bytes) -> None:
    """Replace planned settings or PNG data atomically with private permissions."""

    path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=".workstation-manager-", dir=path.parent)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            content = (
                data
                if isinstance(data, bytes)
                else (json.dumps(data, ensure_ascii=False, separators=(",", ":")) + "\n").encode("utf-8")
            )
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def _apply_theme(preferences: dict, colors: object) -> None:
    """Use the declared main color as Brave's native palette seed."""

    if colors is None:
        return
    if (
        not isinstance(colors, list)
        or not 1 <= len(colors) <= 3
        or any(not isinstance(color, str) or re.fullmatch(r"#[0-9A-Fa-f]{6}", color) is None for color in colors)
    ):
        raise ValueError("Browser theme_colors must contain one to three #RRGGBB colors")
    # SkColor is opaque ARGB stored in a signed integer preference. Chromium
    # derives the remaining palette; secondary colors remain vault metadata.
    color = int(colors[0][1:], 16) - 0x1000000
    theme = _object(_object(preferences, "browser"), "theme")
    if preferences.get("syncing_theme_prefs_migrated_to_non_syncing") is not True and any(
        key in theme for key in ("user_color", "color_variant", "is_grayscale", "color_scheme")
    ):
        raise ValueError("Open Brave once to migrate legacy theme settings, then close it and retry")
    extension_theme = _object(_object(preferences, "extensions"), "theme")
    if extension_theme.get("id", "") not in {"", "user_color_theme_id", "autogenerated_theme_id"}:
        raise ValueError("Reset the custom theme in Brave, then close it and retry profile colors")
    theme.update(user_color2=color, color_variant2=1)
    if theme.get("is_grayscale2", False) is not False:
        theme["is_grayscale2"] = False
    extension_theme["id"] = "user_color_theme_id"
    if extension_theme.get("system_theme", 0) != 0:
        extension_theme["system_theme"] = 0


def _browser_process_arguments(process: Path) -> list[str]:
    """Read native argv or Brave's flattened process title without shell evaluation."""

    arguments = os.fsdecode((process / "cmdline").read_bytes()).rstrip("\0").split("\0")
    if len(arguments) == 1 and " " in arguments[0]:
        executable, flags = arguments[0].split(" ", 1)
        # Brave preserves spaces in values when rewriting its process title.
        # Split at switch boundaries so profile roots containing spaces stay intact.
        return [executable, *re.split(r"\s+(?=--[A-Za-z])", flags)]
    return arguments


def _brave_running(proc_root: Path = Path("/proc")) -> bool:
    """Detect this user's Brave processes even when a lock is missing."""

    for process in proc_root.iterdir():
        if not process.name.isdigit():
            continue
        try:
            if process.stat().st_uid != os.geteuid():
                continue
            command = _browser_process_arguments(process)
            executable = Path(command[0]).name
            if executable in {"brave", "brave-browser", "brave-browser-stable"}:
                return True
        except (OSError, ValueError):
            # A process can exit between listing it and reading its command line.
            continue
    return False


def _profile_paths(root: Path, profiles: list[dict]) -> Iterator[tuple[Path, dict]]:
    """Resolve unique profile identities and reject linked profile directories."""

    planner = BrowserProfilePathsPlanner()
    ids = set()
    directories = set()
    for declaration in profiles:
        profile_id = planner.validate_profile_id(declaration["id"])
        path = Path(planner.build_profile_directory(str(root), profile_id, declaration.get("directory")))
        if profile_id in ids or path.name in directories:
            raise ValueError("Browser profile IDs and directories must be unique")
        ids.add(profile_id)
        directories.add(path.name)
        if path.is_symlink():
            raise ValueError(f"Refusing symlinked browser profile: {path.name}")
        yield path, {**declaration, "id": profile_id}


def _plan_avatar(path: Path, preferences: dict, entry: dict, value: object) -> list[tuple[Path, dict | bytes]]:
    """Select a validated avatar and plan its file replacement only when needed."""

    avatar = decode_avatar_png(value)
    avatar_path = path / AVATAR_FILENAME
    if avatar_path.is_symlink():
        raise ValueError(f"Refusing symlinked browser avatar: {path.name}")
    entry.update(
        gaia_picture_file_name=AVATAR_FILENAME,
        use_gaia_picture=True,
        is_using_default_avatar=False,
    )
    _object(preferences, "profile")["using_gaia_avatar"] = True
    if not avatar_path.exists() or avatar_path.read_bytes() != avatar:
        return [(avatar_path, avatar)]
    return []


def _plan_profile(
    path: Path, declaration: dict, info_cache: dict, replace_names: bool
) -> list[tuple[Path, dict | bytes]]:
    """Register a profile and plan changes while preserving browser-owned settings."""

    label = declaration.get("label") or declaration["id"]
    if not isinstance(label, str) or any(ord(char) < 32 for char in label):
        raise ValueError("Browser profile labels must be single-line strings")
    preferences_path = path / "Preferences"
    preferences = _read_json(preferences_path)
    original_preferences = json.dumps(preferences, sort_keys=True)
    if not preferences_path.exists():
        preferences = {"profile": {"name": label, "using_default_name": False}}
    _apply_theme(preferences, declaration.get("theme_colors"))
    # Setup preserves names; an explicit remote reconciliation replaces them.
    profile_preferences = preferences.get("profile", {})
    if not isinstance(profile_preferences, dict):
        raise ValueError("Expected a JSON object for profile")
    if path.name not in info_cache:
        info_cache[path.name] = {
            "name": profile_preferences.get("name", label),
            "is_using_default_name": False,
        }
    if replace_names:
        _object(preferences, "profile").update(name=label, using_default_name=False)
        _object(info_cache, path.name).update(name=label, is_using_default_name=False)
    planned_files = []
    if declaration.get("avatar_png") is not None:
        planned_files.extend(_plan_avatar(path, preferences, _object(info_cache, path.name), declaration["avatar_png"]))
    if json.dumps(preferences, sort_keys=True) != original_preferences:
        planned_files.append((preferences_path, preferences))
    return planned_files


def seed_browser_profiles(
    user_data_dir: str, profiles: list[dict], check_mode: bool = False, *, replace_names: bool = False
) -> bool:
    """Register profiles and restore their declared native theme color and avatar.

    Existing names change only with explicit replace_names approval.
    Brave owns other settings after creation, including pinned tabs and Sync.
    Check mode computes the complete plan but never creates directories or files.
    """

    if not profiles:
        return False
    root = Path(user_data_dir)
    if not root.is_absolute() or root.is_symlink():
        raise ValueError("Browser user data directory must be absolute and must not be a symlink")
    local_state_path = root / "Local State"
    local_state = _read_json(local_state_path)
    original_local_state = json.dumps(local_state, sort_keys=True)
    profile_state = _object(local_state, "profile")
    info_cache = _object(profile_state, "info_cache")
    planned_files = []
    for path, declaration in _profile_paths(root, profiles):
        planned_files.extend(_plan_profile(path, declaration, info_cache, replace_names))
    profile_state.setdefault("last_used", next(iter(info_cache)))
    if json.dumps(local_state, sort_keys=True) != original_local_state:
        planned_files.append((local_state_path, local_state))
    if planned_files and (os.path.lexists(root / "SingletonLock") or _brave_running()):
        raise ValueError("Close Brave completely before changing profiles; a Brave process or SingletonLock is present")
    if planned_files and not check_mode:
        root.mkdir(mode=0o700, parents=True, exist_ok=True)
        for path, data in planned_files:
            _write_file(path, data)
    return bool(planned_files)
