---
- name: Export the local GPG secret key
  become: "{{ workstation_manager_use_become }}"
  become_user: "{{ workstation_manager_resolved.user.name }}"
  ansible.builtin.command:
    argv:
      - gpg
      - --batch
      - --armor
      - --export-secret-keys
      - "{{ item }}"
  environment:
    HOME: "{{ workstation_manager_resolved.user.home }}"
    GNUPGHOME: "{{ workstation_manager_resolved.user.home }}/.gnupg"
  register: workstation_backup_secret_manager_gpg_private_key
  changed_when: false
  check_mode: false
  no_log: true

- name: Export the local GPG public key
  become: "{{ workstation_manager_use_become }}"
  become_user: "{{ workstation_manager_resolved.user.name }}"
  ansible.builtin.command:
    argv:
      - gpg
      - --batch
      - --armor
      - --export
      - "{{ item }}"
  environment:
    HOME: "{{ workstation_manager_resolved.user.home }}"
    GNUPGHOME: "{{ workstation_manager_resolved.user.home }}/.gnupg"
  register: workstation_backup_secret_manager_gpg_public_key
  changed_when: false
  check_mode: false
  no_log: true

- name: Export the local GPG ownertrust database
  become: "{{ workstation_manager_use_become }}"
  become_user: "{{ workstation_manager_resolved.user.name }}"
  ansible.builtin.command:
    argv:
      - gpg
      - --batch
      - --export-ownertrust
  environment:
    HOME: "{{ workstation_manager_resolved.user.home }}"
    GNUPGHOME: "{{ workstation_manager_resolved.user.home }}/.gnupg"
  register: workstation_backup_secret_manager_gpg_ownertrust
  changed_when: false
  check_mode: false
  no_log: true

- name: Record the local GPG key for synchronization
  ansible.builtin.set_fact:
    workstation_backup_local_gpg_keys: >-
      {{
        (workstation_backup_local_gpg_keys | default([]))
        + [
            {
              'fingerprint': item,
              'private_key': workstation_backup_secret_manager_gpg_private_key.stdout,
              'public_key': workstation_backup_secret_manager_gpg_public_key.stdout,
              'ownertrust': (
                workstation_backup_secret_manager_gpg_ownertrust.stdout_lines
                | select('match', '^' ~ item ~ ':')
                | first
                | default(none)
              )
            }
          ]
      }}
  no_log: true
