---
name: Main - Continuous Integration

"on":
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  clean:
    uses: hoverkraft-tech/ci-github-container/.github/workflows/prune-pull-requests-images-tags.yml@77f98ab8773b824eca7ed3f94e3e9c8b8af5875c # v0.36.1
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: read
    with:
      images: '["tooling"]'

  ci:
    name: Continuous Integration
    uses: ./.github/workflows/__shared-ci.yml
    permissions:
      actions: read
      contents: read
      id-token: write
      issues: read
      packages: write
      pull-requests: read
      security-events: write
      statuses: write
    secrets: inherit
