---
name: Main - Continuous Integration

"on":
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  clean:
    uses: hoverkraft-tech/ci-github-container/.github/workflows/prune-pull-requests-images-tags.yml@c9088e8447c5a8be45157e17701023fc50ccb1c0 # v0.37.2
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: read
    with:
      images: '["tooling"]'

  ci:
    name: Continuous Integration
    uses: ./.github/workflows/__shared-ci.yml
    permissions:
      actions: read
      contents: read
      id-token: write
      issues: read
      packages: write
      pull-requests: read
      security-events: write
      statuses: write
    secrets: inherit
