---
# Renovate Updates
# ==========================
# Workflow to run Renovate for updating Ansible dependencies.

name: Renovate Updates
on:
  workflow_dispatch:
  schedule:
    # Runs "at 04:00, only on Friday" (see https://crontab.guru)
    - cron: "0 4 * * 5"

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      security-events: write
      checks: write
      statuses: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: renovatebot/github-action@693b9ef15eec82123529a37c782242f091365961 # v46.1.14
        with:
          configurationFile: .github/renovate/renovate-config.json5
          token: ${{ github.token }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository}}
